// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DevelopmentFirebaseOptions.currentPlatform,
/// );
/// ```
class DevelopmentFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DevelopmentFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4bec-Lm2xtG4-U7-eGQMcJLYFOXwNd4E',
    appId: '1:79562440860:android:e4234de1e749268a74ad59',
    messagingSenderId: '79562440860',
    projectId: 'bns360-dev-f06f3',
    storageBucket: 'bns360-dev-f06f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSRXF09SacfoT54XHqhnFsleXNyO5hZGk',
    appId: '1:79562440860:ios:610c7e96657749fc74ad59',
    messagingSenderId: '79562440860',
    projectId: 'bns360-dev-f06f3',
    storageBucket: 'bns360-dev-f06f3.appspot.com',
    iosBundleId: 'com.example.bns360GraduationProject',
  );
}
