// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: ProductionFirebaseOptions.currentPlatform,
/// );
/// ```
class ProductionFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DevelopmentFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiWgWlVxNQBPM4_nYPXJwH4u8CG075Mmw',
    appId: '1:185023782037:android:1e42d36edc1c7eab8dcf9c',
    messagingSenderId: '185023782037',
    projectId: 'bns360-prod-99000',
    storageBucket: 'bns360-prod-99000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9X1MKI75ufQYAjmm1nTnY3JGmMwZEJaY',
    appId: '1:185023782037:ios:095b45480231d8148dcf9c',
    messagingSenderId: '185023782037',
    projectId: 'bns360-prod-99000',
    storageBucket: 'bns360-prod-99000.appspot.com',
    iosBundleId: 'com.example.bns360GraduationProject',
  );
}
