platform :android do
  desc "Lane for Firebase distribution - Development"
  lane :distribute_development do
    sh "flutter clean"
    sh "flutter build apk --debug --flavor development --target lib/main_development.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:79562440860:android:e4234de1e749268a74ad59",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-development-release.apk",
      testers: "radyhaggag11@gmail.com, radyhaggag50@gmail.com",
      release_notes: "First Firebase Fastlane distribution for development"
    )  
  end

  desc "Lane for Firebase distribution - Production"
  lane :distribute_production do
    increment_production_version
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:185023782037:android:1e42d36edc1c7eab8dcf9c",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "radyhaggag11@gmail.com, radyhaggag50@gmail.com",
      release_notes: "First Firebase Fastlane distribution for production"
    )  
  end

  desc "Lane for Increment the app version - Development"
  lane :increment_development_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:79562440860:android:e4234de1e749268a74ad59",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
    # This to update version code on android/app/build.gradle
    increment_version_code(
      version_code: latest_release[:buildVersion].to_i + 1,
    )
    flutter_build_increment # This to update version code on pubspec.yaml
  end

  desc "Lane for Increment the app version - Production"
  lane :increment_production_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:185023782037:android:1e42d36edc1c7eab8dcf9c",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
    )
    # This to update version code on android/app/build.gradle
    increment_version_code(
      version_code: latest_release[:buildVersion].to_i + 1,
    )
    flutter_build_increment # This to update version code on pubspec.yaml
  end
  lane :increment_app_version_by_lastest_google_play_release do
    version_code = google_play_track_version_codes(
      package_name: "com.bns360.bns360",
      track: "internal",
      json_key: "Add the path here"
    )
    
    version_code_play_store = version_code[0].to_i
    update_version_code = version_code_play_store + 1
    
    increment_version_code(
      version_code: update_version_code.to_i
    )
  end

  lane :deploy_to_play_store do 
    sh "flutter clean"
    sh "flutter build appbundle"  
    gradle(task: 'bundleRelease')
    # Upload to internal test
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true,
      release_status: 'draft'
    )
  end
end