name: Build and distrbute to firebase app distrubtion --Development (Android)

on:
  push:
    branches:
      - main

jobs:
  distrubte_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Check repo code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android

      - name: Build and distrubte
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android distribute_development
        working-directory: android
